language: elixir

dist: trusty

branches:
  only:
    - master

matrix:
  include:
    - otp_release: 18.3
      elixir: 1.2.6
    - otp_release: 19.3
      elixir: 1.4.2

sudo: false

script: mix test --trace
